In [3]:
import numpy as np
import nashpy as nash

Considerando um jogo de 2 players, cada jogador tem 2 estratégias, Player A  pode jogar em baixo ou em cima e o Player B pode jogar pela esquerda ou pela direita essa matriz é conhecida como Matriz do pagamento, Player A é o jogador de linha e o Player B é o jogador Coluna

Por Exemplo: Se o Player A jogar "Baixo" e o Player B jogar Esquerda, Os pagamentos serão:
* Player A - 4
* Player B - 2

Para o Player A sempre será melhor jogar para Baixo  por seu "payoff" (4/2) sempre será maior que Para Cima (2/0)

Para o Player B sempre será melhor  jogar para a esquerda, visto que o payoff" (4/2) sempre será maior que Para Cima (2/0)

A estratégia de equilibrio é Player A jogar para baixo e Player B jogar para esquerda <Conceito da estratégia dominante>

#### Estratégia dominante

Existe uma estratégia otimizada pata cada jogador.  Não importa qual a escolha do Player B, o Player A deve sempre escolher "Baixo" e não importa a escolha do Player A, o Player B sempre deve escolher "Esquerda".

#### Equilibrio de Nash

In [6]:
A = np.array([[2,0],[4,2]])
B = np.array([[4,2],[2,0]])
game1 = nash.Game(A,B)
game1

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [4 2]]

Column player:
[[4 2]
 [2 0]]

In [5]:
equilibria  = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([1., 0.]))


In [12]:
A = np.array([[4,0],[0,2]])
B = np.array([[2,0],[0,4]])
game2 = nash.Game(A,B)
game2

equilibria  = game2.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.66666667, 0.33333333]), array([0.33333333, 0.66666667]))


In [13]:
sigma_r = np.array([.67,.33])
sigma_c = np.array([.33,.67])
pd = nash.Game(A, B)
pd[sigma_r, sigma_c]

array([1.3266, 1.3266])

In [14]:
A = np.array([[-3,0],[-6,-1]]) 
B = np.array([[-3,-6],[0,-1]]) 
game4 = nash.Game(A,B)
game4

equilibria = game4.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([1., 0.]))
